name: eb_example
description: Event Bus example
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox/eb
publish_to: 'none'
version: 0.0.1-dev


environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Architecture and IoC
  eb:
    git:
      url: 'https://github.com/PlugFox/eb.git'
      ref: dev

  # Utility
  l: ^1.1.1
  meta: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #build_runner: ^1.10.2
  #build_web_compilers: ^2.11.0
  #build_test: ^1.2.1
  #test: ^1.15.3


flutter:
  uses-material-design: true
