name: eb
description: Event Bus architecture
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox/eb
version: 0.0.1-dev

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  meta: ^1.0.4

dev_dependencies:
  test: ^1.15.3